name: Run it on action

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/25 16 * * *'
  watch:
    types: [started]
jobs:
  run-it:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    name: Run it on action
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
      - name: Run
        run: |
          php run
